services:
    admin.general.vacancy:
        class: App\Admin\VacancyAdmin
        arguments: [~, App\Entity\Vacancy, ~]
        tags:
            - { name: sonata.admin, group: Общее, manager_type: orm, label: Вакансии }
        public: true
    admin.general.main_page:
        class: App\Admin\MainPageAdmin
        arguments: [~, App\Entity\MainPage, ~, "@app.file_upload"]
        tags:
            - { name: sonata.admin, group: Общее, manager_type: orm, label: Главная }
        public: true
    admin.general.contacts_page:
        class: App\Admin\ContactsPageAdmin
        arguments: [~, App\Entity\ContactsPage, ~]
        tags:
            - { name: sonata.admin, group: Общее, manager_type: orm, label: Контакты }
        public: true
    admin.general.promocode:
        class: App\Admin\PromoCodeAdmin
        arguments: [~, App\Entity\PromoCode, ~]
        tags:
            - { name: sonata.admin, group: Товары, manager_type: orm, label: Промокод }
        public: true