sonata_admin:

    title: 'Панель администратора'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    templates:
        layout: sonata_admin_base_layout.html.twig
#            -
#              position: right
#              type: sonata.block.service.text

    security:
        handler: sonata.admin.security.handler.role

        role_super_admin: ROLE_SUPER_ADMIN
#        acl_user_manager: App\Manager\AclUserManager

#    assets:
#        extra_stylesheets:
#            - build/css/admin/admin.css

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
