sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
#            -
#              position: right
#              type: sonata.block.service.text

#    security:
#        handler: sonata.admin.security.handler.role

#        role_super_admin: ROLE_SUPER_ADMIN

#    assets:
#        extra_stylesheets:
#            - build/css/admin/admin.css

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]