twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    # I have add this line:
    exception_controller: Symfony\Bundle\TwigBundle\Controller\ExceptionController::showAction
    globals:
        default_image_directory: '/images/default/'
        image_directory: '/images/'
#    exception_controller: App\Controller\ExceptionController::showException