# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
imports:
    - { resource: ./packages/admin_blocks.yaml }
    - { resource: ./packages/bundles_init.yaml }

parameters:
    locale: 'ru'
    upload_directory: '%kernel.project_dir%/public/images'
    upload_image_directory: '/images/'


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Form,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Symfony\Bundle\TwigBundle\Controller\ExceptionController:
        alias: twig.controller.exception
        public: true

    app.file_upload:
        class:  App\Upload\FileUpload
        arguments: ['@images_filesystem']
        public: true

    app.import.import_xml_data:
        class:  App\Import\XMLDataImporter
        arguments: []
        public: true